imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        enabled: true
        handler_id: null
        storage_factory_id: 'session.storage.factory.native'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 604800
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
