var classes = [
    {
        "name": "App\\Tests\\WebTestCaseHelperTrait",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "assertFlashBagContains",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "assertIsAuthenticated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getClient",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\KernelBrowser",
            "Symfony\\Bundle\\FrameworkBundle\\KernelBrowser",
            "ReflectionMethod"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 27,
        "vocabulary": 13,
        "volume": 99.91,
        "difficulty": 1.91,
        "effort": 190.74,
        "level": 0.52,
        "bugs": 0.03,
        "time": 11,
        "intelligentContent": 52.33,
        "number_operators": 6,
        "number_operands": 21,
        "number_operators_unique": 2,
        "number_operands_unique": 11,
        "cloc": 31,
        "loc": 53,
        "lloc": 22,
        "mi": 102.9,
        "mIwoC": 56.58,
        "commentWeight": 46.32,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 81.23,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 0.7,
        "totalSystemComplexity": 243.7,
        "package": "App\\Tests\\",
        "pageRank": 0.14,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Tests\\Task\\CreateTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "testShouldCreateTaskAndRedirectToShowPage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldRaiseHttpAccessDeniedAndRedirectToLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldRaiseFormErrors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideInvalidFormData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUpClientAndLogin",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFormData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "implements": [],
        "lcom": 4,
        "length": 64,
        "vocabulary": 29,
        "volume": 310.91,
        "difficulty": 3,
        "effort": 932.73,
        "level": 0.33,
        "bugs": 0.1,
        "time": 52,
        "intelligentContent": 103.64,
        "number_operators": 12,
        "number_operands": 52,
        "number_operators_unique": 3,
        "number_operands_unique": 26,
        "cloc": 33,
        "loc": 90,
        "lloc": 57,
        "mi": 84.43,
        "mIwoC": 44.11,
        "commentWeight": 40.32,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 169.25,
        "totalStructuralComplexity": 1014,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 1015.5,
        "package": "App\\Tests\\Task\\",
        "pageRank": 0.14,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Tests\\Task\\UpdateTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "testShouldUpdateTaskAndRedirectToShowPage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldRaiseFormErrors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideInvalidFormData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUpClientAndLogin",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFormData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "implements": [],
        "lcom": 3,
        "length": 59,
        "vocabulary": 29,
        "volume": 286.62,
        "difficulty": 2.77,
        "effort": 793.72,
        "level": 0.36,
        "bugs": 0.1,
        "time": 44,
        "intelligentContent": 103.5,
        "number_operators": 11,
        "number_operands": 48,
        "number_operators_unique": 3,
        "number_operands_unique": 26,
        "cloc": 42,
        "loc": 90,
        "lloc": 48,
        "mi": 89.56,
        "mIwoC": 45.98,
        "commentWeight": 43.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.26,
        "relativeSystemComplexity": 169.26,
        "totalStructuralComplexity": 845,
        "totalDataComplexity": 1.29,
        "totalSystemComplexity": 846.29,
        "package": "App\\Tests\\Task\\",
        "pageRank": 0.14,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Tests\\Task\\DeleteTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "testShouldDeleteTaskAndRedirectToListPage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldRaiseHttpAccessDenied",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testAdminCanDeleteOtherUserTask",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUpClientAndLogin",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase",
            "Symfony\\Bundle\\FrameworkBundle\\KernelBrowser",
            "Exception"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "implements": [],
        "lcom": 1,
        "length": 120,
        "vocabulary": 23,
        "volume": 542.83,
        "difficulty": 9.16,
        "effort": 4971.16,
        "level": 0.11,
        "bugs": 0.18,
        "time": 276,
        "intelligentContent": 59.27,
        "number_operators": 33,
        "number_operands": 87,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 9,
        "loc": 69,
        "lloc": 60,
        "mi": 68.33,
        "mIwoC": 41.79,
        "commentWeight": 26.54,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 100.11,
        "totalStructuralComplexity": 400,
        "totalDataComplexity": 0.45,
        "totalSystemComplexity": 400.45,
        "package": "App\\Tests\\Task\\",
        "pageRank": 0.14,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Tests\\Task\\ListTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "testShouldListTasks",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldRaiseHttpAccessDeniedAndRedirectToLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUpClientAndLogin",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase",
            "Symfony\\Bundle\\FrameworkBundle\\KernelBrowser"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "implements": [],
        "lcom": 2,
        "length": 28,
        "vocabulary": 15,
        "volume": 109.39,
        "difficulty": 2.5,
        "effort": 273.48,
        "level": 0.4,
        "bugs": 0.04,
        "time": 15,
        "intelligentContent": 43.76,
        "number_operators": 8,
        "number_operands": 20,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 53.37,
        "mIwoC": 53.37,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 64.11,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 192.33,
        "package": "App\\Tests\\Task\\",
        "pageRank": 0.14,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Tests\\Security\\RegistrationTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "testShouldRegisterUserAndRedirectToIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldRaiseFormErrors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldRaiseUsernameAlreadyUsedError",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideInvalidFormData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFormData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "implements": [],
        "lcom": 5,
        "length": 88,
        "vocabulary": 35,
        "volume": 451.38,
        "difficulty": 3.7,
        "effort": 1671.51,
        "level": 0.27,
        "bugs": 0.15,
        "time": 93,
        "intelligentContent": 121.89,
        "number_operators": 9,
        "number_operands": 79,
        "number_operators_unique": 3,
        "number_operands_unique": 32,
        "cloc": 31,
        "loc": 79,
        "lloc": 48,
        "mi": 85.86,
        "mIwoC": 44.6,
        "commentWeight": 41.26,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 100.27,
        "totalStructuralComplexity": 500,
        "totalDataComplexity": 1.36,
        "totalSystemComplexity": 501.36,
        "package": "App\\Tests\\Security\\",
        "pageRank": 0.14,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Tests\\Security\\LoginTest",
        "interface": false,
        "abstract": false,
        "final": true,
        "methods": [
            {
                "name": "testShouldAuthenticatedUserAndRedirectToIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldNotAuthenticateUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testShouldLogoutUserAndRedirectToLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideInvalidFormData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFormData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase"
        ],
        "implements": [],
        "lcom": 5,
        "length": 50,
        "vocabulary": 21,
        "volume": 219.62,
        "difficulty": 3.58,
        "effort": 786.96,
        "level": 0.28,
        "bugs": 0.07,
        "time": 44,
        "intelligentContent": 61.29,
        "number_operators": 7,
        "number_operands": 43,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 11,
        "loc": 61,
        "lloc": 50,
        "mi": 76.98,
        "mIwoC": 46.41,
        "commentWeight": 30.57,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.37,
        "relativeSystemComplexity": 36.37,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 1.86,
        "totalSystemComplexity": 181.86,
        "package": "App\\Tests\\Security\\",
        "pageRank": 0.14,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]