@startuml Logout
    title Logout
    skinparam backgroundColor #EEEEEE
    skinparam shadowing true

    actor User
    control Server
    database Database
    User --> Server : Request Logout page
    activate Server  #lightblue
    Server --> User : Clears session data
    Server --> User : Redirect to homepage
    Server --> Database : Display flash message
    deactivate Server 
@enduml
