<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBX7qgHZ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBX7qgHZ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBX7qgHZ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBX7qgHZ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBX7qgHZ\App_KernelProdContainer([
    'container.build_hash' => 'BX7qgHZ',
    'container.build_id' => '01012c25',
    'container.build_time' => 1695294587,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBX7qgHZ');
