<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJcZ5Ly2\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJcZ5Ly2/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJcZ5Ly2.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJcZ5Ly2\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJcZ5Ly2\App_KernelTestDebugContainer([
    'container.build_hash' => 'JcZ5Ly2',
    'container.build_id' => '69f215ba',
    'container.build_time' => 1695736653,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJcZ5Ly2');
