<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::indexAction'], ['_locale' => 'en|fr'], [['text', '/']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::loginAction'], ['_locale' => 'en|fr'], [['text', '/login']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logoutCheck'], ['_locale' => 'en|fr'], [['text', '/logout']], [], [], []],
    'task_list' => [[], ['_controller' => 'App\\Controller\\TaskController::listAction'], ['_locale' => 'en|fr'], [['text', '/tasks']], [], [], []],
    'task_create' => [[], ['_controller' => 'App\\Controller\\TaskController::createAction'], ['_locale' => 'en|fr'], [['text', '/tasks/create']], [], [], []],
    'task_edit' => [['id'], ['_controller' => 'App\\Controller\\TaskController::editAction'], ['_locale' => 'en|fr'], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'task_toggle' => [['id'], ['_controller' => 'App\\Controller\\TaskController::toggleTaskAction'], ['_locale' => 'en|fr'], [['text', '/toggle'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'task_delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::deleteTaskAction'], ['_locale' => 'en|fr'], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tasks']], [], [], []],
    'task_list_done' => [[], ['_controller' => 'App\\Controller\\TaskController::listTasksDone'], ['_locale' => 'en|fr'], [['text', '/tasks/done']], [], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\UserController::listAction'], ['_locale' => 'en|fr'], [['text', '/users/']], [], [], []],
    'user_create' => [[], ['_controller' => 'App\\Controller\\UserController::createAction'], ['_locale' => 'en|fr'], [['text', '/users/create']], [], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::editAction'], ['_locale' => 'en|fr'], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+', '_locale' => 'en|fr'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
