<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xlHI7a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xlHI7a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xlHI7a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xlHI7a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xlHI7a\App_KernelDevDebugContainer([
    'container.build_hash' => '5xlHI7a',
    'container.build_id' => '73246ffb',
    'container.build_time' => 1695724193,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xlHI7a');
